# Generated by Django 5.1.2 on 2024-12-01 06:13

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '3. Страна',
                'verbose_name_plural': '3. Страна',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PackageFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '2. Упаковка',
                'verbose_name_plural': '2. Упаковка',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='flowers.category', verbose_name='Родитель категории')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': '1. Основная категория',
                'verbose_name_plural': '1. Основная категория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flowers.category',),
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_outer_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Внешний диаметр головки (мм)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('cashback', models.IntegerField(blank=True, default=10, null=True, verbose_name='Кешбак')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество цветов')),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True, verbose_name='В наличи или нет')),
                ('showcase_online', models.BooleanField(blank=True, default=False, null=True, verbose_name='Витрина Онлайн')),
                ('is_popular', models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярное')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='Новинки')),
                ('stock_number', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент акции')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.category', verbose_name='Категория')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.countryflower', verbose_name='Страна')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.packageflower', verbose_name='Упаковка')),
            ],
            options={
                'verbose_name': '4. Цветы',
                'verbose_name_plural': '4. Цветы',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompoundyofFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав букета')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_compound', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesofFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower_images/', verbose_name='Изображение')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_image', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityofFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Количество букета')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_quantity', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flower_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_review', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
            options={
                'verbose_name': '5. Отзыв',
                'verbose_name_plural': '5. Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SizesofFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название размер букета')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_size', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категория')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'flowers_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryFlowerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название страна')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.countryflower')),
            ],
            options={
                'verbose_name': '3. Страна Translation',
                'db_table': 'flowers_countryflower_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FlowerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название цвета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('plantation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Плантация')),
                ('sort', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cорт')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.flower')),
            ],
            options={
                'verbose_name': '4. Цветы Translation',
                'db_table': 'flowers_flower_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PackageFlowerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название упаковка')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.packageflower')),
            ],
            options={
                'verbose_name': '2. Упаковка Translation',
                'db_table': 'flowers_packageflower_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
