# Generated by Django 5.1.2 on 2024-12-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='plant_length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Длина растения'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price_per_box',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за коробку'),
        ),
    ]
