# Generated by Django 5.1.2 on 2024-12-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower_plant_length_flower_price_per_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesofflower',
            name='flower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowers.flower', verbose_name='Выбрать цветок'),
        ),
    ]
