# Generated by Django 5.1.2 on 2024-12-01 07:24

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flower_stem_height_flower_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Карусели баннеров',
                'verbose_name_plural': 'Карусели баннеров',
                'ordering': ['id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BannerCarouselTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.bannercarousel')),
            ],
            options={
                'verbose_name': 'Карусели баннеров Translation',
                'db_table': 'flowers_bannercarousel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
