# Generated by Django 5.1.2 on 2024-12-01 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_bannercarousel_bannercarouseltranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercarousel',
            options={'ordering': ['id'], 'verbose_name': '5. Карусели баннеров', 'verbose_name_plural': '5. Карусели баннеров'},
        ),
        migrations.AlterModelOptions(
            name='bannercarouseltranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '5. Карусели баннеров Translation'},
        ),
        migrations.CreateModel(
            name='LiketoFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_like', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
            options={
                'verbose_name': '6. Лайк за цветы ',
                'verbose_name_plural': '6. Лайк за цветы',
                'ordering': ['id'],
            },
        ),
    ]
