# Generated by Django 5.1.2 on 2024-12-01 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_alter_bannercarousel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liketoflower',
            options={'ordering': ['id'], 'verbose_name': 'Лайк за цветы ', 'verbose_name_plural': 'Лайк за цветы'},
        ),
        migrations.CreateModel(
            name='ViewUsertoFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_views', to='flowers.flower', verbose_name='Выбрать цветок')),
            ],
            options={
                'verbose_name': 'Увиденные цветы ',
                'verbose_name_plural': 'Увиденные цветы',
                'ordering': ['id'],
            },
        ),
    ]
