# Generated by Django 5.1.2 on 2024-12-16 15:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_liketoflower_options_viewusertoflower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('cashback', models.IntegerField(blank=True, default=10, null=True, verbose_name='Кешбак')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество цветов')),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True, verbose_name='В наличи или нет')),
                ('showcase_online', models.BooleanField(blank=True, default=False, null=True, verbose_name='Витрина Онлайн')),
                ('is_popular', models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярное')),
                ('is_new', models.BooleanField(blank=True, default=False, null=True, verbose_name='Новинки')),
                ('stock_number', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент акции')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '6. Воздушные шары',
                'verbose_name_plural': '6. Воздушные шары',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImagesofBalloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='balloon_images/', verbose_name='Изображение')),
                ('balloon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_balloon', to='flowers.balloon', verbose_name='Выбрать')),
            ],
        ),
        migrations.CreateModel(
            name='BalloonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название цвета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flowers.balloon')),
            ],
            options={
                'verbose_name': '6. Воздушные шары Translation',
                'db_table': 'flowers_balloon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
