# Generated by Django 5.1.2 on 2024-12-14 10:19

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowers', '0007_alter_liketoflower_options_viewusertoflower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDeliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статус Доставить',
                'verbose_name_plural': 'Статус Доставить',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TypeRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '2. Тип получателя',
                'verbose_name_plural': '2. Тип получателя',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlacingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('adress', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('flat', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('is_call', models.BooleanField(blank=True, default=False, null=True, verbose_name='')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='')),
                ('cashback', models.FloatField(blank=True, default=0, null=True, verbose_name='')),
                ('deliver_price', models.FloatField(blank=True, default=0, null=True, verbose_name='')),
                ('is_promo_code', models.BooleanField(blank=True, default=False, null=True, verbose_name='')),
                ('comment2', models.TextField(blank=True, max_length=250, null=True, verbose_name='Название баннера')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('status_deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.statusdeliver', verbose_name='Статус Доставить')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.typerecipient', verbose_name='Тип получателя')),
            ],
            options={
                'verbose_name': '1. Заказанная продукция',
                'verbose_name_plural': '1. Заказанная продукция',
            },
        ),
        migrations.CreateModel(
            name='OrderFlowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Высота стебля')),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_order', to='flowers.flower', verbose_name='Выбрать цветок')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flower_order', to='order.placingorder', verbose_name='Выбрать цветок')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDeliverTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус Доставить')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='order.statusdeliver')),
            ],
            options={
                'verbose_name': 'Статус Доставить Translation',
                'db_table': 'order_statusdeliver_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TypeRecipientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип Получатель')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='order.typerecipient')),
            ],
            options={
                'verbose_name': '2. Тип получателя Translation',
                'db_table': 'order_typerecipient_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
