# Generated by Django 5.1.2 on 2024-12-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusdeliver',
            options={'verbose_name': '3. Статус Доставить', 'verbose_name_plural': '3. Статус Доставить'},
        ),
        migrations.AlterModelOptions(
            name='statusdelivertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '3. Статус Доставить Translation'},
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='cashback',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ваш кешбэк 10%'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='comment2',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий к заказу / текст записки'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='deliver_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='flat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Квартира/офис, подъезд, этаж'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='is_call',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Позвонить перед выездом курьера'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='is_promo_code',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Применить кешбэк или нет'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='status_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.statusdeliver', verbose_name='Когда доставляем?'),
        ),
        migrations.AlterField(
            model_name='placingorder',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ИТОГО к оплате'),
        ),
    ]
