# Generated by Django 5.1.2 on 2024-12-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_statusdeliver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placingorder',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
