# Generated by Django 5.1.2 on 2024-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_placingorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderflowers',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
