name: Deploy to Server Flower APP

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh root@213.139.211.234 << EOF
          cd /var/www/Flowers
          git pull
          source /var/www/Flowers/env/bin/activate  # If using Python
          pip install -r requirements.txt    # Install dependencies
          python manage.py migrate          # Run migrations
          python manage.py collectstatic --noinput  # Collect static files
          systemctl restart gunicorn         # Restart application server
          EOF
